import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { cookies } from "next/headers";
import { getMessagesForLocale, Locale } from "@/lib/i18n";
import { defaultLocale } from "@/i18n.config";
import { PageLoader } from "@/components/ui/page-loader";
import { WebSocketInitializer } from "@/components/WebSocketInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  
  // 1. Determina lo stato di autenticazione sul server
  const isAuthenticated = cookieStore.has("refresh_token");
  
  // 2. Determina la lingua corrente dal cookie sul server
  const locale = (cookieStore.get("NEXT_LOCALE")?.value || defaultLocale) as Locale;

  // 3. Carica i messaggi di traduzione sul server
  const messages = await getMessagesForLocale(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Passa i dati pre-caricati con nomi chiari */}
        <Providers
          isAuthenticated={isAuthenticated}
          serverLocale={locale}
          serverMessages={messages}
        >
          <WebSocketInitializer />
          {children}
        </Providers>
        <PageLoader />
      </body>
    </html>
  );
}
