 'use client';

import { GalleryVerticalEnd } from "lucide-react"
import { LoginForm } from "@/components/login-form"
import Image from "next/image"
import { useLogin } from "@/hooks/useAuth";
import { LoginCredentials } from "@/types";


export function LoginClient() {
    const login = useLogin();

    const handleLogin = (form: LoginCredentials) => {
        login.mutate(form);
    };

    return (
        <div className="grid min-h-svh lg:grid-cols-2">
            <div className="flex flex-col gap-4 p-6 md:p-10">
                <div className="flex justify-center gap-2 md:justify-start">
                    <a href="#" className="flex items-center gap-2 font-medium">
                        <div className="bg-primary text-primary-foreground flex size-6 items-center justify-center rounded-md">
                            <GalleryVerticalEnd className="size-4" />
                        </div>
                        Generated By Zion.
                    </a>
                </div>
                <div className="flex flex-1 items-center justify-center">
                    <div className="w-full max-w-xs">
                        <LoginForm
                            onLoginSubmit={handleLogin}
                            isLoading={login.isPending}
                            error={login.isError ? 'Credenziali non valide' : undefined}
                        />
                    </div>
                </div>
            </div>
            <div className="bg-muted relative hidden lg:block flex items-center justify-center">
                <Image
                    src="/images/logo.jpg"
                    alt="Logo della mia azienda"
                    width={400}
                    height={400}
                    className="rounded-lg"
                />
            </div>
        </div>
    );
}
    
    