# Generated by Django 5.2.6 on 2025-10-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataloggerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'running'), ('stopped', 'stopped'), ('starting', 'starting'), ('error', 'error'), ('unknown', 'unknown')], default='unknown', max_length=50)),
                ('details', models.TextField(blank=True, help_text='Additional information or error message', null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, help_text='Time of last status update')),
            ],
            options={
                'verbose_name': 'Datalogger status',
                'verbose_name_plural': 'Datalogger statuses',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('serial_number', models.CharField(help_text='Device serial number', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Device IP address', unpack_ipv4=True)),
                ('software_version', models.CharField(help_text='Device software version', max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Time of last detection')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-last_seen'],
            },
        ),
    ]
