# Generated by Django 5.2.7 on 2025-10-15 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_site_latitude_alter_site_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_host', models.CharField(max_length=255)),
                ('broker_port', models.IntegerField(default=1883)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('client_id_prefix', models.CharField(max_length=50)),
                ('keep_alive_interval', models.IntegerField(default=60)),
                ('retry_attempts', models.IntegerField(default=5)),
                ('retry_delay', models.IntegerField(default=5)),
                ('max_retry_delay', models.IntegerField(default=300)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ca_cert_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('error', 'Error'), ('disabled', 'Disabled')], default='disconnected', max_length=20)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('connection_errors', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'MQTT Connection',
                'verbose_name_plural': 'MQTT Connections',
            },
        ),
        migrations.CreateModel(
            name='ConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('heartbeat_missed', 'Heartbeat Missed'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mqtt_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.mqttconnection')),
            ],
            options={
                'verbose_name': 'Connection Log',
                'verbose_name_plural': 'Connection Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('consecutive_misses', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Sensor Device',
                'verbose_name_plural': 'Sensor Devices',
                'ordering': ['site', 'device_name'],
                'unique_together': {('site', 'device_name')},
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('raw_data', models.JSONField()),
                ('acc_x', models.FloatField(blank=True, null=True)),
                ('acc_y', models.FloatField(blank=True, null=True)),
                ('acc_z', models.FloatField(blank=True, null=True)),
                ('incli_x', models.FloatField(blank=True, null=True)),
                ('incli_y', models.FloatField(blank=True, null=True)),
                ('mag_x', models.FloatField(blank=True, null=True)),
                ('mag_y', models.FloatField(blank=True, null=True)),
                ('mag_z', models.FloatField(blank=True, null=True)),
                ('gyro_x', models.FloatField(blank=True, null=True)),
                ('gyro_y', models.FloatField(blank=True, null=True)),
                ('gyro_z', models.FloatField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.sensordevice')),
            ],
            options={
                'verbose_name': 'Sensor Data',
                'verbose_name_plural': 'Sensor Data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_device', '-timestamp'], name='mqtt_sensor_sensor__92065a_idx')],
            },
        ),
    ]
