# Generated by Django 5.2.7 on 2025-10-15 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_pattern', models.CharField(help_text="Pattern topic senza site_code (es: 'datalogger_o/heartbeat', 'alerts', 'config/response')", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Se il topic è attivo per la subscription')),
                ('qos_level', models.IntegerField(choices=[(0, 'QoS 0 - Fire and Forget'), (1, 'QoS 1 - At Least Once'), (2, 'QoS 2 - Exactly Once')], default=0, help_text='Quality of Service level per questo topic')),
                ('description', models.TextField(blank=True, help_text='Descrizione del topic e del suo utilizzo')),
                ('auto_retry', models.BooleanField(default=True, help_text='Riprova automaticamente subscription se fallisce')),
                ('priority', models.IntegerField(default=0, help_text='Priorità topic (0=normale, 1=alta, -1=bassa)')),
                ('max_message_size', models.IntegerField(blank=True, help_text='Dimensione massima messaggio in bytes (null=illimitato)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mqtt_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='mqtt.mqttconnection')),
            ],
            options={
                'verbose_name': 'MQTT Topic',
                'verbose_name_plural': 'MQTT Topics',
                'ordering': ['priority', 'topic_pattern'],
                'indexes': [models.Index(fields=['mqtt_connection', 'is_active'], name='mqtt_mqttto_mqtt_co_634109_idx'), models.Index(fields=['topic_pattern'], name='mqtt_mqttto_topic_p_a56dad_idx')],
                'unique_together': {('mqtt_connection', 'topic_pattern')},
            },
        ),
    ]
