# Generated by Django 5.2.7 on 2025-10-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0002_mqtttopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtttopic',
            name='last_subscribed_at',
            field=models.DateTimeField(blank=True, help_text='Ultima subscription riuscita', null=True),
        ),
        migrations.AddField(
            model_name='mqtttopic',
            name='subscription_count',
            field=models.IntegerField(default=0, help_text='Numero totale di subscription effettuate'),
        ),
    ]
