# Generated by Django 5.2.7 on 2025-10-15 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0003_mqtttopic_last_subscribed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttconnection',
            name='client_id_prefix',
            field=models.CharField(help_text="Prefisso per client ID e topic MQTT (es: 'sito_001', 'company/site_a')", max_length=50, validators=[django.core.validators.RegexValidator(message='Client ID prefix può contenere solo lettere, numeri, underscore, slash e trattini', regex='^[a-zA-Z0-9_/-]+$')]),
        ),
        migrations.AlterField(
            model_name='mqtttopic',
            name='topic_pattern',
            field=models.CharField(help_text="Pattern topic senza prefisso (es: 'datalogger_o/heartbeat', 'alerts', 'config/response')", max_length=255),
        ),
    ]
