# Generated by Django 5.2.7 on 2025-10-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0004_alter_mqttconnection_client_id_prefix_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectionLog',
        ),
    ]
