# Generated by Django 5.2.7 on 2025-10-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0005_remove_connectionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttconnection',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Se disabilitata, questa connessione MQTT viene ignorata dal sistema'),
        ),
    ]
