# Generated by Django 5.2.7 on 2025-10-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0006_add_enabled_field'),
        ('sites', '0004_site_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('cpu_model', models.CharField(blank=True, max_length=255)),
                ('cpu_cores', models.IntegerField(blank=True, null=True)),
                ('cpu_frequency', models.FloatField(blank=True, null=True)),
                ('total_memory', models.BigIntegerField(blank=True, null=True)),
                ('total_storage', models.BigIntegerField(blank=True, null=True)),
                ('used_storage', models.BigIntegerField(blank=True, null=True)),
                ('available_storage', models.BigIntegerField(blank=True, null=True)),
                ('os_name', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('kernel_version', models.CharField(blank=True, max_length=100)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('boot_time', models.DateTimeField(blank=True, null=True)),
                ('cpu_usage_percent', models.FloatField(blank=True, null=True)),
                ('memory_usage_percent', models.FloatField(blank=True, null=True)),
                ('disk_usage_percent', models.FloatField(blank=True, null=True)),
                ('network_interfaces', models.JSONField(blank=True, default=dict)),
                ('cpu_temperature', models.FloatField(blank=True, null=True)),
                ('system_sensors', models.JSONField(blank=True, default=dict)),
                ('python_version', models.CharField(blank=True, max_length=50)),
                ('installed_packages', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_info', to='sites.site')),
            ],
            options={
                'verbose_name': 'System Information',
                'verbose_name_plural': 'System Information',
                'ordering': ['-last_updated'],
            },
        ),
    ]
