# Generated by Django 5.2.7 on 2025-10-17 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0007_systeminfo'),
        ('sites', '0004_site_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datalogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('label', models.CharField(help_text="Nome editabile dall'utente, default=serial_number", max_length=255)),
                ('datalogger_type', models.CharField(help_text='monstro, adaq, etc.', max_length=50)),
                ('instance_number', models.PositiveIntegerField(help_text='Numero istanza dal topic (1, 2, 3...)')),
                ('is_online', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_communication', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('total_heartbeats', models.IntegerField(default=0)),
                ('missed_heartbeats', models.IntegerField(default=0)),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('last_downtime_start', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_dataloggers', to='sites.site')),
            ],
            options={
                'verbose_name': 'Datalogger',
                'verbose_name_plural': 'Dataloggers',
                'ordering': ['site__name', 'datalogger_type', 'instance_number'],
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(help_text="Nome editabile dall'utente, default=serial_number", max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('is_online', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_communication', models.DateTimeField(blank=True, null=True)),
                ('cpu_usage_percent', models.FloatField(blank=True, null=True)),
                ('memory_usage_percent', models.FloatField(blank=True, null=True)),
                ('disk_usage_percent', models.FloatField(blank=True, null=True)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway', to='sites.site')),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateways',
                'ordering': ['site__name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='device_name dal payload', max_length=100)),
                ('label', models.CharField(help_text="Nome editabile dall'utente, default=serial_number", max_length=255)),
                ('sensor_type', models.CharField(blank=True, max_length=50)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50)),
                ('is_online', models.BooleanField(default=False)),
                ('last_reading', models.DateTimeField(blank=True, null=True)),
                ('last_timestamp_1', models.DateTimeField(blank=True, null=True)),
                ('last_data_1', models.JSONField(blank=True, default=dict)),
                ('last_timestamp_2', models.DateTimeField(blank=True, null=True)),
                ('last_data_2', models.JSONField(blank=True, default=dict)),
                ('last_timestamp_3', models.DateTimeField(blank=True, null=True)),
                ('last_data_3', models.JSONField(blank=True, default=dict)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_readings', models.IntegerField(default=0)),
                ('min_value_ever', models.FloatField(blank=True, null=True)),
                ('max_value_ever', models.FloatField(blank=True, null=True)),
                ('min_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('max_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('consecutive_misses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datalogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='mqtt.datalogger')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'ordering': ['datalogger__site__name', 'datalogger__label', 'label'],
            },
        ),
        migrations.AddIndex(
            model_name='datalogger',
            index=models.Index(fields=['site', 'datalogger_type', 'instance_number'], name='mqtt_datalo_site_id_2aa4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='datalogger',
            index=models.Index(fields=['serial_number'], name='mqtt_datalo_serial__29129c_idx'),
        ),
        migrations.AddIndex(
            model_name='datalogger',
            index=models.Index(fields=['is_online'], name='mqtt_datalo_is_onli_1af348_idx'),
        ),
        migrations.AddIndex(
            model_name='datalogger',
            index=models.Index(fields=['last_heartbeat'], name='mqtt_datalo_last_he_185452_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datalogger',
            unique_together={('site', 'serial_number')},
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['datalogger', 'is_online'], name='mqtt_sensor_datalog_1c4cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['serial_number'], name='mqtt_sensor_serial__0c8bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['last_reading'], name='mqtt_sensor_last_re_fcafde_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['last_timestamp_1'], name='mqtt_sensor_last_ti_ede342_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('datalogger', 'serial_number')},
        ),
    ]
