# Generated by Django 5.2.7 on 2025-10-17 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0008_datalogger_gateway_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalogger',
            name='label',
            field=models.CharField(help_text="Nome editabile dall'utente, default=serial_number", max_length=255, validators=[django.core.validators.RegexValidator(message='Label non può contenere caratteri HTML pericolosi', regex='^[^<>\\"\\\'&]+$')]),
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='missed_heartbeats',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='serial_number',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Serial number può contenere solo lettere, numeri, underscore e trattini', regex='^[a-zA-Z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='total_heartbeats',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='uptime_percentage',
            field=models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='cpu_usage_percent',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='disk_usage_percent',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='label',
            field=models.CharField(help_text="Nome editabile dall'utente, default=serial_number", max_length=255, validators=[django.core.validators.RegexValidator(message='Label non può contenere caratteri HTML pericolosi', regex='^[^<>\\"\\\'&]+$')]),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='memory_usage_percent',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Serial number può contenere solo lettere, numeri, underscore e trattini', regex='^[a-zA-Z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='uptime_seconds',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='consecutive_misses',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='label',
            field=models.CharField(help_text="Nome editabile dall'utente, default=serial_number", max_length=255, validators=[django.core.validators.RegexValidator(message='Label non può contenere caratteri HTML pericolosi', regex='^[^<>\\"\\\'&]+$')]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='serial_number',
            field=models.CharField(help_text='device_name dal payload', max_length=100, validators=[django.core.validators.RegexValidator(message='Serial number può contenere solo lettere, numeri, underscore, punti e trattini', regex='^[a-zA-Z0-9_.-]+$')]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='total_messages',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='total_readings',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='uptime_percentage',
            field=models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
