# Generated by Django 5.2.7 on 2025-10-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0009_alter_datalogger_label_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensordevice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sensordevice',
            name='site',
        ),
        migrations.RemoveField(
            model_name='systeminfo',
            name='site',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.DeleteModel(
            name='SensorDevice',
        ),
        migrations.DeleteModel(
            name='SystemInfo',
        ),
    ]
