# Generated by Django 5.2.7 on 2025-10-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0010_alter_sensordevice_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogger',
            name='device_id',
            field=models.CharField(blank=True, help_text='Device ID dal topic (1, 2, 3...)', max_length=50),
        ),
        migrations.AddField(
            model_name='datalogger',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Ultimo heartbeat ricevuto (ENHANCED)', null=True),
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='datalogger_type',
            field=models.CharField(blank=True, help_text='monstro, adaq, etc. - dal topic', max_length=50),
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='instance_number',
            field=models.PositiveIntegerField(blank=True, help_text='LEGACY: Numero istanza dal topic (1, 2, 3...)', null=True),
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='last_communication',
            field=models.DateTimeField(blank=True, help_text='LEGACY: compatibilità', null=True),
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='LEGACY: compatibilità', null=True),
        ),
    ]
