# Generated by Django 5.2.7 on 2025-10-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0011_datalogger_device_id_datalogger_last_seen_at_and_more'),
        ('sites', '0004_site_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_path', models.CharField(help_text="Topic completo ricevuto (es: 'sito_001/datalogger/heartbeat')", max_length=500)),
                ('topic_pattern', models.CharField(help_text="Pattern del topic senza prefix (es: 'datalogger/heartbeat')", max_length=500)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('message_count', models.IntegerField(default=1)),
                ('sample_payload', models.JSONField(blank=True, help_text='Campione del payload per analisi struttura', null=True)),
                ('payload_size_avg', models.FloatField(blank=True, help_text='Dimensione media payload in bytes', null=True)),
                ('message_frequency_seconds', models.FloatField(blank=True, help_text='Frequenza media messaggi in secondi', null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='True se questo topic ha logica di processing implementata')),
                ('processor_name', models.CharField(blank=True, help_text='Nome del processore che gestisce questo topic', max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_topics', to='sites.site')),
            ],
            options={
                'verbose_name': 'Discovered Topic',
                'verbose_name_plural': 'Discovered Topics',
                'ordering': ['-last_seen_at', 'topic_path'],
                'indexes': [models.Index(fields=['site', 'topic_pattern'], name='mqtt_discov_site_id_2a5e9b_idx'), models.Index(fields=['last_seen_at'], name='mqtt_discov_last_se_e128b3_idx'), models.Index(fields=['is_processed'], name='mqtt_discov_is_proc_f63a0b_idx')],
                'unique_together': {('site', 'topic_path')},
            },
        ),
    ]
