# Generated by Django 5.2.7 on 2025-10-20 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0012_discoveredtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='cpu_usage_percent',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='disk_usage_percent',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='memory_usage_percent',
        ),
        migrations.AddField(
            model_name='gateway',
            name='cpu_load_percent',
            field=models.FloatField(blank=True, help_text='Carico CPU in percentuale', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='gateway',
            name='disk_free_gb',
            field=models.FloatField(blank=True, help_text='Spazio disco libero in GB', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='gateway',
            name='disk_percent_used',
            field=models.FloatField(blank=True, help_text='Spazio disco utilizzato in percentuale', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='gateway',
            name='disk_total_gb',
            field=models.FloatField(blank=True, help_text='Spazio disco totale in GB', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='gateway',
            name='os_version',
            field=models.CharField(blank=True, help_text='Sistema operativo e versione', max_length=255),
        ),
        migrations.AddField(
            model_name='gateway',
            name='ram_percent_used',
            field=models.FloatField(blank=True, help_text='RAM utilizzata in percentuale', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='gateway',
            name='ram_total_gb',
            field=models.FloatField(blank=True, help_text='RAM totale in GB', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='gateway',
            name='ram_used_gb',
            field=models.FloatField(blank=True, help_text='RAM utilizzata in GB', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='gateway',
            name='system_uptime',
            field=models.CharField(blank=True, help_text="Uptime formato stringa (es: '14 days, 3:24:30')", max_length=100),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='uptime_seconds',
            field=models.BigIntegerField(blank=True, help_text='Uptime calcolato in secondi per ordinamento', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
