# Generated by Django 5.2.7 on 2025-10-20 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0013_remove_gateway_cpu_usage_percent_and_more'),
        ('sites', '0004_site_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='sites.site'),
        ),
    ]
