# Generated by Django 5.2.7 on 2025-10-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0014_alter_gateway_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogger',
            name='gateway',
            field=models.ForeignKey(blank=True, help_text='Gateway di appartenenza', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataloggers', to='mqtt.gateway'),
        ),
    ]
