# Generated by Django 5.2.7 on 2025-10-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0016_add_versioning_and_dynamic_monitoring'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mqttapiversionusage',
            new_name='mqtt_mqttap_version_5b5fb6_idx',
            old_name='mqtt_version_site_idx',
        ),
        migrations.RenameIndex(
            model_name='mqttapiversionusage',
            new_name='mqtt_mqttap_topic_p_49cfd1_idx',
            old_name='mqtt_version_topic_idx',
        ),
        migrations.RenameIndex(
            model_name='mqttdowntimeevent',
            new_name='mqtt_mqttdo_device__ba89e5_idx',
            old_name='mqtt_downtime_device_idx',
        ),
        migrations.RenameIndex(
            model_name='mqttdowntimeevent',
            new_name='mqtt_mqttdo_site_id_84e320_idx',
            old_name='mqtt_downtime_site_idx',
        ),
        migrations.RenameIndex(
            model_name='mqttdowntimeevent',
            new_name='mqtt_mqttdo_offline_89f1b0_idx',
            old_name='mqtt_downtime_timeline_idx',
        ),
        migrations.RemoveField(
            model_name='datalogger',
            name='connection_status',
        ),
        migrations.RemoveField(
            model_name='datalogger',
            name='expected_heartbeat_interval',
        ),
        migrations.RemoveField(
            model_name='datalogger',
            name='last_offline_at',
        ),
        migrations.RemoveField(
            model_name='datalogger',
            name='last_status_change',
        ),
        migrations.RemoveField(
            model_name='datalogger',
            name='mqtt_api_version',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='connection_status',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='expected_heartbeat_interval',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='last_offline_at',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='last_status_change',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='mqtt_api_version',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='connection_status',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='expected_heartbeat_interval',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='last_offline_at',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='last_status_change',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='mqtt_api_version',
        ),
    ]
