# Generated by Django 5.2.7 on 2025-10-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0017_rename_mqtt_version_site_idx_mqtt_mqttap_version_5b5fb6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogger',
            name='connection_status',
            field=models.CharField(choices=[('online', 'Online'), ('warning', 'Warning'), ('offline', 'Offline'), ('gateway_offline', 'Gateway Offline'), ('unknown', 'Unknown')], default='online', help_text='Current connection status', max_length=20),
        ),
        migrations.AddField(
            model_name='datalogger',
            name='expected_heartbeat_interval',
            field=models.IntegerField(default=60, help_text='Expected heartbeat interval in seconds'),
        ),
        migrations.AddField(
            model_name='datalogger',
            name='last_offline_at',
            field=models.DateTimeField(blank=True, help_text='When device went offline', null=True),
        ),
        migrations.AddField(
            model_name='datalogger',
            name='last_status_change',
            field=models.DateTimeField(blank=True, help_text='When status last changed', null=True),
        ),
        migrations.AddField(
            model_name='datalogger',
            name='mqtt_api_version',
            field=models.CharField(default='v1.0.0', help_text='MQTT API version used by this datalogger', max_length=20),
        ),
        migrations.AddField(
            model_name='gateway',
            name='connection_status',
            field=models.CharField(choices=[('online', 'Online'), ('warning', 'Warning'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='online', help_text='Current connection status', max_length=20),
        ),
        migrations.AddField(
            model_name='gateway',
            name='expected_heartbeat_interval',
            field=models.IntegerField(default=60, help_text='Expected heartbeat interval in seconds'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='last_offline_at',
            field=models.DateTimeField(blank=True, help_text='When device went offline', null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='last_status_change',
            field=models.DateTimeField(blank=True, help_text='When status last changed', null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='mqtt_api_version',
            field=models.CharField(default='v1.0.0', help_text='MQTT API version used by this gateway', max_length=20),
        ),
        migrations.AddField(
            model_name='sensor',
            name='connection_status',
            field=models.CharField(choices=[('online', 'Online'), ('warning', 'Warning'), ('offline', 'Offline'), ('datalogger_offline', 'Datalogger Offline'), ('gateway_offline', 'Gateway Offline'), ('unknown', 'Unknown')], default='online', help_text='Current connection status', max_length=20),
        ),
        migrations.AddField(
            model_name='sensor',
            name='expected_heartbeat_interval',
            field=models.IntegerField(default=60, help_text='Expected heartbeat interval in seconds'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_offline_at',
            field=models.DateTimeField(blank=True, help_text='When device went offline', null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_status_change',
            field=models.DateTimeField(blank=True, help_text='When status last changed', null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='mqtt_api_version',
            field=models.CharField(default='v1.0.0', help_text='MQTT API version used by this sensor', max_length=20),
        ),
    ]
