# Generated by Django 5.2.7 on 2025-10-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0018_add_missing_versioning_fields'),
        ('sites', '0005_alter_site_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalogger',
            options={'ordering': ['site__name', 'datalogger_type', 'device_id'], 'verbose_name': 'Datalogger', 'verbose_name_plural': 'Dataloggers'},
        ),
        migrations.RemoveIndex(
            model_name='datalogger',
            name='mqtt_datalo_site_id_2aa4bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='datalogger',
            name='mqtt_datalo_last_he_185452_idx',
        ),
        migrations.RemoveField(
            model_name='datalogger',
            name='instance_number',
        ),
        migrations.RemoveField(
            model_name='datalogger',
            name='last_communication',
        ),
        migrations.RemoveField(
            model_name='datalogger',
            name='last_heartbeat',
        ),
        migrations.AddIndex(
            model_name='datalogger',
            index=models.Index(fields=['site', 'datalogger_type', 'device_id'], name='mqtt_datalo_site_id_e0e261_idx'),
        ),
        migrations.AddIndex(
            model_name='datalogger',
            index=models.Index(fields=['last_seen_at'], name='mqtt_datalo_last_se_8c26ab_idx'),
        ),
    ]
