# Generated by Django 5.2.7 on 2025-10-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0019_remove_legacy_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='last_communication',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='last_heartbeat',
        ),
    ]
