# Generated by Django 5.2.8 on 2025-11-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0021_add_retry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttconnection',
            name='ssl_insecure',
            field=models.BooleanField(default=False, help_text='Se abilitato, disabilita la verifica del certificato SSL (insecure)'),
        ),
    ]
