# Generated by Django 5.2.8 on 2025-11-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0022_mqttconnection_ssl_insecure'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogger',
            name='acquisition_status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('paused', 'Paused'), ('error', 'Error'), ('unknown', 'Unknown')], default='running', help_text='Acquisition/measurement status', max_length=20),
        ),
    ]
