# Generated by Django 5.2.8 on 2025-11-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0022_mqttconnection_ssl_insecure'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='last_seen_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='Ultimo messaggio ricevuto dal gateway'
            ),
        ),
    ]
