# Generated by Django 5.2.8 on 2025-11-26 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0023_add_last_seen_at_to_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttconnection',
            name='client_id_prefix',
            field=models.CharField(help_text="Prefisso per identificare univocamente la connessione MQTT (es: 'sito_001', 'company_site_a'). Usato per costruire il client_id univoco e topic di sistema come LWT.", max_length=50, validators=[django.core.validators.RegexValidator(message='Client ID prefix può contenere solo lettere, numeri, underscore, slash e trattini', regex='^[a-zA-Z0-9_/-]+$')]),
        ),
        migrations.AlterField(
            model_name='mqtttopic',
            name='topic_pattern',
            field=models.CharField(help_text="Topic pattern completo MQTT (es: 'sito_001/datalogger_o/heartbeat', 'company/site/alerts', 'prefix/+/heartbeat', 'prefix/#'). Supporta wildcards: + (singolo livello), # (multi-livello)", max_length=255, validators=[django.core.validators.RegexValidator(message='Topic pattern MQTT può contenere solo lettere, numeri, underscore, slash, trattini e wildcards MQTT (+, #)', regex='^[a-zA-Z0-9_/\\-+#]+$')]),
        ),
    ]
