# Generated by Django 5.2.8 on 2025-11-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0024_alter_mqtt_topic_pattern_independence'),
        ('sites', '0005_alter_site_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('exception_type', models.CharField(blank=True, max_length=255)),
                ('exception_traceback', models.TextField(blank=True)),
                ('broker_host', models.CharField(blank=True, max_length=255)),
                ('retry_attempt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MQTT Connection Log',
                'verbose_name_plural': 'MQTT Connection Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MqttParsingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(max_length=500)),
                ('parser_name', models.CharField(blank=True, max_length=100)),
                ('error_type', models.CharField(choices=[('VALIDATION_ERROR', 'JSON Validation Error'), ('PARSE_ERROR', 'Topic Parse Error'), ('DB_ERROR', 'Database Error'), ('UNKNOWN_ERROR', 'Unknown Error')], max_length=50)),
                ('error_message', models.TextField()),
                ('exception_type', models.CharField(blank=True, max_length=255)),
                ('exception_traceback', models.TextField(blank=True)),
                ('payload_sample', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MQTT Parsing Log',
                'verbose_name_plural': 'MQTT Parsing Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='discoveredtopic',
            name='mqtt_discov_is_proc_f63a0b_idx',
        ),
        migrations.RenameField(
            model_name='discoveredtopic',
            old_name='is_processed',
            new_name='is_processable',
        ),
        migrations.RenameField(
            model_name='mqttconnection',
            old_name='is_enabled',
            new_name='is_active',
        ),
        migrations.AddIndex(
            model_name='discoveredtopic',
            index=models.Index(fields=['is_processable'], name='mqtt_discov_is_proc_cd2200_idx'),
        ),
        migrations.AddField(
            model_name='mqttconnectionlog',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mqtt.mqttconnection'),
        ),
        migrations.AddField(
            model_name='mqttparsinglog',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_parsing_logs', to='sites.site'),
        ),
        migrations.AddIndex(
            model_name='mqttconnectionlog',
            index=models.Index(fields=['connection', '-timestamp'], name='mqtt_mqttco_connect_463cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='mqttconnectionlog',
            index=models.Index(fields=['level', '-timestamp'], name='mqtt_mqttco_level_136e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='mqttparsinglog',
            index=models.Index(fields=['site', '-timestamp'], name='mqtt_mqttpa_site_id_faa6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='mqttparsinglog',
            index=models.Index(fields=['error_type', '-timestamp'], name='mqtt_mqttpa_error_t_a8d64d_idx'),
        ),
        migrations.AddIndex(
            model_name='mqttparsinglog',
            index=models.Index(fields=['topic'], name='mqtt_mqttpa_topic_6cc3e9_idx'),
        ),
    ]
