# Generated by Django 5.2.8 on 2025-11-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0023_datalogger_acquisition_status'),
        ('mqtt', '0024_alter_mqtt_topic_pattern_independence'),
    ]

    operations = [
    ]
