# Generated by Django 5.2.8 on 2025-11-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0025_mqttconnectionlog_mqttparsinglog_and_more'),
        ('sites', '0005_alter_site_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discoveredtopic',
            name='mqtt_discov_is_proc_cd2200_idx',
        ),
        migrations.AddField(
            model_name='discoveredtopic',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se False, il topic non viene processato (utile per manutenzione)'),
        ),
        migrations.AddIndex(
            model_name='discoveredtopic',
            index=models.Index(fields=['is_processable', 'is_active'], name='mqtt_discov_is_proc_b1c20d_idx'),
        ),
    ]
