# Generated by Django 5.2.8 on 2025-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0025_merge_20251126_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalogger',
            name='acquisition_status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('paused', 'Paused'), ('error', 'Error'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='running', help_text='Acquisition/measurement status', max_length=20),
        ),
    ]
