# Generated by Django 5.2.7 on 2025-10-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userpreferences',
            constraint=models.CheckConstraint(condition=models.Q(('theme__in', ['light', 'dark', 'system'])), name='theme_must_be_valid_choice'),
        ),
    ]
