# Generated by Django 5.2.7 on 2025-10-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userpreferences_theme_must_be_valid_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='show_resize_handle',
            field=models.CharField(choices=[('show', 'Show'), ('hide', 'Hide')], default='show', max_length=4),
        ),
        migrations.AddConstraint(
            model_name='userpreferences',
            constraint=models.CheckConstraint(condition=models.Q(('show_resize_handle__in', ['show', 'hide'])), name='resize_handle_must_be_valid_choice'),
        ),
    ]
