# Generated by Django 5.2.7 on 2025-10-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userpreferences_show_resize_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='accelerometer_unit',
            field=models.CharField(choices=[('ms2', 'm/s²'), ('g', 'g')], default='ms2', max_length=3),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='inclinometer_unit',
            field=models.CharField(choices=[('deg', 'Degrees'), ('rad', 'Radians')], default='deg', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='userpreferences',
            constraint=models.CheckConstraint(condition=models.Q(('accelerometer_unit__in', ['ms2', 'g'])), name='accelerometer_unit_must_be_valid_choice'),
        ),
        migrations.AddConstraint(
            model_name='userpreferences',
            constraint=models.CheckConstraint(condition=models.Q(('inclinometer_unit__in', ['deg', 'rad'])), name='inclinometer_unit_must_be_valid_choice'),
        ),
    ]
