# Generated by Django 5.2.8 on 2025-11-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userpreferences_accelerometer_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('it', 'Italiano'), ('en', 'English')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=6),
        ),
        migrations.AddConstraint(
            model_name='userpreferences',
            constraint=models.CheckConstraint(condition=models.Q(('language__in', ['it', 'en'])), name='language_must_be_valid_choice'),
        ),
    ]
