# Generated by Django 5.2.7 on 2025-10-09 11:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('site_type', models.CharField(choices=[('bridge', 'Bridge'), ('building', 'Building'), ('tunnel', 'Tunnel'), ('dam', 'Dam'), ('tower', 'Tower'), ('pipeline', 'Pipeline'), ('other', 'Other')], default='other', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude coordinate (-90 to 90 degrees)', max_digits=10, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude coordinate (-180 to 180 degrees)', max_digits=10, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('customer_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['customer_name'], name='sites_site_custome_a02f8e_idx'), models.Index(fields=['site_type'], name='sites_site_site_ty_6e0946_idx'), models.Index(fields=['is_active'], name='sites_site_is_acti_2a8915_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSiteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_site_accesses', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Site Access',
                'verbose_name_plural': 'User Site Accesses',
                'ordering': ['site__name'],
                'unique_together': {('user', 'site')},
            },
        ),
    ]
