# Generated by Django 5.2.7 on 2025-10-09 12:05
from decimal import Decimal # Utilizza sempre questo nei campi models.DecimalField
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(decimal_places=12, default=Decimal(42.44534164063), help_text='Latitude coordinate (-90 to 90 degrees)', max_digits=17, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(decimal_places=12, default=Decimal(14.19865273854), help_text='Longitude coordinate (-180 to 180 degrees)', max_digits=17, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
