# Generated by Django 5.2.7 on 2025-10-10 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sites', '0002_alter_site_latitude_alter_site_longitude'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='site',
            new_name='custom_site_custome_58b4c1_idx',
            old_name='sites_site_custome_a02f8e_idx',
        ),
        migrations.RenameIndex(
            model_name='site',
            new_name='custom_site_site_ty_4b9f97_idx',
            old_name='sites_site_site_ty_6e0946_idx',
        ),
        migrations.RenameIndex(
            model_name='site',
            new_name='custom_site_is_acti_a0efd9_idx',
            old_name='sites_site_is_acti_2a8915_idx',
        ),
        migrations.AlterField(
            model_name='usersiteaccess',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='custom_sites.site'),
        ),
    ]
