# Generated by Django 5.2.7 on 2025-10-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_datalogger_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='code',
            field=models.CharField(help_text="Site code for MQTT topics (e.g., 'sito_001')", max_length=50, null=True, unique=True),
        ),
    ]
