# Generated by Django 5.2.7 on 2025-10-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_site_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(help_text='Unique immutable site code for database queries', max_length=50, null=True, unique=True),
        ),
    ]
